# Template: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build On Linux

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup XMake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Configure XMake
      working-directory: ${{github.workspace}}
      run: xmake f -m release

    - name: Build Targets
      working-directory: ${{github.workspace}}
      run: xmake build

    - name: Install Targets
      working-directory: ${{github.workspace}}
      run: xmake install

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: install
        path: build/linux/x86_64/release/install
        include-hidden-files: true
        if-no-files-found: error
