# Release On Multiple Platform
name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows
            arch: x86_64
            plat: windows
            xmake-arch: x64
            runs-on: windows-latest

          - os: ubuntu
            arch: x86_64
            plat: linux
            xmake-arch: x86_64
            runs-on: ubuntu-latest

          - os: ubuntu
            arch: arm64
            plat: linux
            xmake-arch: arm64
            runs-on: ubuntu-24.04-arm

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup XMake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    # 生成 Debug 和 Release 包，使用 xmake 原生 package 机制生成编译完成的二进制包。
    # build/packages/
    # └── x
    #     └── xmake-project
    #         └── linux
    #             └── x86_64
    #                 └── release
    #                     ├── include/
    #                     ├── lib/
    #                     └── bin/
    - name: Generate Packages
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        for mode in debug release
        do
          echo "Building ${mode} package..."

          xmake f \
            -m ${mode} \
            -p ${{ matrix.plat }} \
            -a ${{ matrix.xmake-arch }} \
            -y

          xmake build

          xmake package
        done

    # 使用 xmake package 生成的 Debug/Release 二进制包合并为一个平台包。
    # 原始结构：
    #
    # xmake-project/
    # └── linux/
    #     └── x86_64/
    #         ├── debug/
    #         │   ├── include/
    #         │   ├── lib/
    #         │   └── bin/
    #         │
    #         └── release/
    #             ├── include/
    #             ├── lib/
    #             └── bin/
    #
    # 转换后：
    #
    # xmake-project-linux-x86_64.tar.gz
    # ├── debug/
    # │   ├── include/
    # │   ├── lib/
    # │   └── bin/
    # │
    # └── release/
    #     ├── include/
    #     ├── lib/
    #     └── bin/
    #
    - name: Archive Platform Package
      shell: bash
      run: |
        tree build/packages/x/xmake-project

        tar czf \
        xmake-project-${{ github.ref_name }}-${{ matrix.plat }}-${{ matrix.xmake-arch }}.tar.gz \
        -C build/packages/x/xmake-project/${{ matrix.plat }}/${{ matrix.xmake-arch }} .

    - name: Upload Platform Package
      uses: actions/upload-artifact@v4
      with:
        name: xmake-project-${{ github.ref_name }}-${{ matrix.plat }}-${{ matrix.xmake-arch }}
        path: "*.tar.gz"
        include-hidden-files: true
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Download Packages
      uses: actions/download-artifact@v4
      with:
        path: assets
        merge-multiple: true

    - name: Display Release Assets
      run: tree assets -a

    # - name: Create Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: assets/*.tar.gz
