name: Unit Test On Windows

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  unit-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup XMake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Configure XMake
      working-directory: ${{github.workspace}}
      run: xmake f -m release --with_gtest=true -y

    - name: Build Targets
      working-directory: ${{github.workspace}}
      run: xmake build

    - name: Run Unit Test
      working-directory: ${{github.workspace}}
      run: xmake test
