name: Update xmake-repo

env:
  PACKAGE_NAME: xmake-project

on:
  release:
    types:
      - published

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Notify xmake-repo
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.XMAKE_REPO_TOKEN }}
        repository: davidingplus/xmake-repo
        event-type: update-package
        client-payload: |
          {
            "package": "${{ env.PACKAGE_NAME }}",
            "repo": "${{ github.repository }}",
            "version": "${{ github.event.release.tag_name }}"
          }
